version: '3.5'

# Example stack for local development
# IMPORTANT: you need to create the docker images first via gradle like this:
# ./gradlew buildDockerImage

services:
  jenkins:
    image: lovelysystems/jenkins:dev
    ports:
     - "8080:8080"
    environment:
      # optional environment variable set here to their defaults for reference
      JENKINS_BASE_URL: 'http://localhost:8080'
      JENKINS_ADMIN_PASSWORD: admin
      JENKINS_ADMIN_EMAIL: 'admin@jenkins.com'
      JENKINS_SLAVE_PORT: 50000
      JENKINS_GITHUB_USER_NAME: jenkins_admin
      JENKINS_GITHUB_USER_PRIVATE_KEY_PATH: /run/secrets/jenkins-github-key
    volumes:
      - ./../job-dsl:/usr/share/jenkins/ref/jobs/seed-job/workspace
      - jenkins_home:/var/jenkins_home
    secrets:
      - jenkins-github-key

volumes:
  jenkins_home:

secrets:
  jenkins-github-key:
    file: ~/.ssh/id_ecdsa


