version: '3.5'

# Example stack for local development
# IMPORTANT: you need to create the docker images first via gradle like this:
# ./gradlew buildDockerImage

services:
  jenkins:
    image: lovelysystems/docker-jenkins:dev
    ports:
     - "8080:8080"
    environment:
      JENKINS_ADMIN_PASSWORD: admin
    volumes:
      - ./volumes/job-dsl:/usr/share/jenkins/ref/jobs/seed-job/workspace:ro
