version: '3.5'

# Example stack for local development
# IMPORTANT: you need to create the docker images first via gradle like this:
# ./gradlew buildDockerImage

services:
  jenkins:
    image: lovelysystems/docker-jenkins:dev
    ports:
     - "8080:8080"
    environment:
      JENKINS_ADMIN_PASSWORD: admin
      JENKINS_SSH_USER_NAME: jenkins
    volumes:
      - ./volumes/job_dsl:/usr/share/jenkins/ref/jobs/seed-job/workspace:ro
    secrets:
      - jenkins_ssh_key
      - source: jenkins_ssh_known_hosts
        target: /etc/ssh/ssh_known_hosts

secrets:
  jenkins_ssh_key:
    file: .ssh/id
  jenkins_ssh_known_hosts:
    file: .ssh/known_hosts
